module vhtml5

import strings
import vperf_core

pub struct ProfiledVCompile {
pub:
	code string
	profile vperf_core.CompilerProfile
}

pub fn compile_to_v(source string, options VEmitOptions) !string {
	return compile_to_v_profiled(source, options, vperf_core.CompilerBudget{})!.code
}

pub fn compile_to_v_profiled(source string, options VEmitOptions, budget vperf_core.CompilerBudget) !ProfiledVCompile {
	start := vperf_core.start_profile()
	doc := parse_document(source)!
	code := emit_v(doc, options)
	return ProfiledVCompile{
		code: code
		profile: vperf_core.finish_compile_profile('vhtml5.compile', start, source.len,
			code.len, doc.node_count(), budget)
	}
}

pub fn emit_v(doc Document, options VEmitOptions) string {
	module_name := if options.module_name.trim_space() == '' { 'compiled_html' } else { options.module_name.trim_space() }
	function_name := if options.function_name.trim_space() == '' { 'load_document' } else { options.function_name.trim_space() }
	mut out := strings.new_builder(2048)
	if options.include_header {
		out.writeln('// Generated by vhtml5. Do not edit by hand.')
	}
	out.writeln('module ${module_name}')
	out.writeln('')
	out.writeln('import vhtml5')
	out.writeln('')
	out.writeln('pub fn ${function_name}() vhtml5.Document {')
	out.writeln('\treturn vhtml5.Document{')
	out.writeln('\t\tdoctype: ${quote_v(doc.doctype)}')
	out.writeln('\t\tchildren: ${emit_nodes(doc.children, 2)}')
	out.writeln('\t\twarnings: ${emit_strings(doc.warnings)}')
	out.writeln('\t}')
	out.writeln('}')
	return out.str()
}

fn emit_nodes(nodes []Node, level int) string {
	if nodes.len == 0 {
		return '[]vhtml5.Node{}'
	}
	indent := tabs(level)
	child_indent := tabs(level + 1)
	mut out := strings.new_builder(nodes.len * 160)
	out.writeln('[')
	for node in nodes {
		out.writeln('${child_indent}vhtml5.Node{')
		out.writeln('${child_indent}\tkind: ${emit_kind(node.kind)}')
		out.writeln('${child_indent}\ttag: ${quote_v(node.tag)}')
		out.writeln('${child_indent}\ttext: ${quote_v(node.text)}')
		out.writeln('${child_indent}\tattrs: ${emit_attrs(node.attrs, level + 2)}')
		out.writeln('${child_indent}\tchildren: ${emit_nodes(node.children, level + 2)}')
		out.writeln('${child_indent}\tself_closing: ${node.self_closing}')
		out.writeln('${child_indent}},')
	}
	out.write_string('${indent}]')
	return out.str()
}

fn emit_attrs(attrs []Attribute, level int) string {
	if attrs.len == 0 {
		return '[]vhtml5.Attribute{}'
	}
	indent := tabs(level)
	child_indent := tabs(level + 1)
	mut out := strings.new_builder(attrs.len * 64)
	out.writeln('[')
	for attr in attrs {
		out.writeln('${child_indent}vhtml5.Attribute{')
		out.writeln('${child_indent}\tname: ${quote_v(attr.name)}')
		out.writeln('${child_indent}\tvalue: ${quote_v(attr.value)}')
		out.writeln('${child_indent}},')
	}
	out.write_string('${indent}]')
	return out.str()
}

fn emit_kind(kind NodeKind) string {
	return match kind {
		.document { 'vhtml5.NodeKind.document' }
		.doctype { 'vhtml5.NodeKind.doctype' }
		.element { 'vhtml5.NodeKind.element' }
		.text { 'vhtml5.NodeKind.text' }
		.comment { 'vhtml5.NodeKind.comment' }
	}
}

fn emit_strings(values []string) string {
	if values.len == 0 {
		return '[]string{}'
	}
	mut escaped := []string{}
	for value in values {
		escaped << quote_v(value)
	}
	return '[' + escaped.join(', ') + ']'
}

fn tabs(count int) string {
	mut value := ''
	for _ in 0 .. count {
		value += '\t'
	}
	return value
}

fn quote_v(value string) string {
	mut out := strings.new_builder(value.len + 8)
	out.write_u8(`'`)
	for i := 0; i < value.len; i++ {
		ch := value[i]
		match ch {
			`\\` { out.write_string('\\\\') }
			`'` { out.write_string("\\'") }
			`\n` { out.write_string('\\n') }
			`\r` { out.write_string('\\r') }
			`\t` { out.write_string('\\t') }
			else { out.write_u8(ch) }
		}
	}
	out.write_u8(`'`)
	return out.str()
}
